{% set name = "htmltools" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/htmltools-{{ version }}.tar.gz
  sha256: 5b731d3be1488b8a6d36952295e38390dbf632744c618a8f0062847e580ac20b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - packaging >=20.9
    - typing-extensions >=3.10.0.0

test:
  imports:
    - htmltools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rstudio/py-htmltools
  summary: Tools for HTML generation and output.
  license: MIT
  license_file:
    - LICENSE
  description: |
    # `htmltools` for Python

    Tools for creating, manipulating, and writing HTML from Python.

    PyPI: [https://pypi.org/project/htmltools](https://pypi.org/project/htmltools)

  doc_url: https://github.com/rstudio/py-htmltools
  dev_url: https://github.com/rstudio/py-htmltools

extra:
  recipe-maintainers:
    - sugatoray

  feedstock-name: py-{{ name|lower }}
